"""
This code is generated by Anthropy's Claude AI.

Discontinuous Galerkin (DG) finite element solver for the linear
stationary transport equation

    L u := mu * du/dz + dlogn(z) * (1-mu^2) * du/dmu + kappa(z) * u = f(mu,z)

on the phase-space domain

    Omega = (-1,1)_mu x (0,Z)_z

with inflow boundary condition u = g(mu,z) on

    Sigma = ([0,1] x {0})  U  ([-1,0] x {Z})

Here dlogn(z) = d(log n)/dz for a given (positive) "density" profile n(z);
only this logarithmic derivative enters the equation.  kappa(z) >= 0 is an
absorption/extinction coefficient and f is a source term.

METHOD
------
This is a genuinely 2D (mu,z) linear advection-reaction problem with
advection field

    b(mu,z) = ( b_mu, b_z ) = ( dlogn(z)*(1-mu^2),  mu )     [ (mu,z) order ]

Because  b_mu = 0  identically at mu = +-1, the edges mu=+-1 are
characteristic (no flux crosses them) and require no boundary condition --
consistent with the problem statement, which only prescribes u on the
inflow portions of the z=0 and z=Z edges.

We discretise with a tensor-product (Q_p) modal Legendre DG method on a
structured rectangular mesh in (mu,z):

  * On each rectangular cell the unknown is a polynomial of degree <= p in
    mu times degree <= p in z, expanded in a tensor Legendre basis.
  * The volume form is kept in *strong* (non-conservative) form, exactly as
    written in the PDE:  a_K(u,v) = int_K (b.grad u) v + kappa u v dx.
  * Inter-element and boundary coupling is introduced only on the INFLOW
    part of each cell boundary, through the standard upwind numerical flux.
    For a cell K with outward normal n, on the inflow set
    d K^- = { b.n < 0 } one adds

        int_{dK^-} (b.n) (u_ext - u_K) v_K ds

    where u_ext is the trace of the upwind neighbour (or the prescribed
    boundary data g on Sigma). This is exactly the strong-form upwind DG
    discretisation of a linear advection-reaction equation and is
    consistent (it vanishes when u_ext = u_K trace of the exact solution).

  * The resulting global linear system is sparse and is solved directly
    with scipy.sparse.linalg.spsolve.

The scheme was verified (see bottom of file, `_manufactured_solution_test`)
against the exact solution available when n(z) = const (dlogn = 0) and
kappa(z) = kappa0 = const, for which the PDE decouples into independent 1D
ODEs along mu = const lines:

    u(mu,z) = 1/kappa0 + (mu - 1/kappa0) * exp(-kappa0*z/mu),      mu>0
    u(mu,z) = 1/kappa0 + (mu - 1/kappa0) * exp(-kappa0*(z-Z)/mu),  mu<0

Author: (generated for the user's DG transport problem)
"""

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
from numpy.polynomial import legendre as L


# ============================================================================
# 1. PROBLEM DATA  -- edit these to change the physical problem
# ============================================================================

Z_DOMAIN = 1.2          # length of the z-domain, Omega = (-1,1) x (0,Z_DOMAIN)


def dlogn_dz(z):
    """d(log n)/dz  -- logarithmic derivative of the background density n(z).

    Only this combination enters the PDE, so the user may supply it
    directly (preferred, for accuracy) instead of n(z) itself.

    Default example:  n(z) = (1+z)^(-2)  =>  log n = -2 log(1+z)
                       =>  dlogn/dz = -2/(1+z)
    """
    z = np.asarray(z, dtype=float)
    return -2.0 / (1.0 + z)


def kappa_func(z):
    """Absorption/extinction coefficient kappa(z) >= 0."""
    z = np.asarray(z, dtype=float)
    return 1.0 + 0.0 * z          # constant kappa = 1 by default


def f_rhs(mu, z):
    """Source term f(mu,z) on the right-hand side of L u = f."""
    return 0.0 + 0.0 * np.asarray(mu, dtype=float)


def g_bc(mu, z):
    """Inflow boundary data, u = g on Sigma.  Problem states u|_Sigma = mu."""
    mu = np.asarray(mu, dtype=float)
    pos = mu>0
    return mu*pos


# ============================================================================
# 2. DISCRETISATION PARAMETERS -- edit these to change mesh/accuracy
# ============================================================================

P_DEG = 3          # polynomial degree in each of mu, z  (tensor product Q_p)
N_MU  = 24         # number of cells in mu in (-1,1)
N_Z   = 24         # number of cells in z  in (0,Z_DOMAIN)

NQ  = 2 * P_DEG + 4   # volume quadrature points per direction
NFQ = 2 * P_DEG + 4   # face quadrature points


# ============================================================================
# 3. REFERENCE-ELEMENT BASIS UTILITIES  (modal Legendre basis on [-1,1])
# ============================================================================

def basis_1d(p, x):
    """Legendre basis P_0..P_p and derivatives, evaluated at points x.

    Returns
    -------
    vals, derivs : ndarray, shape (p+1, len(x))
    """
    x = np.atleast_1d(np.asarray(x, dtype=float))
    n = x.size
    vals = np.zeros((p + 1, n))
    derivs = np.zeros((p + 1, n))
    for i in range(p + 1):
        c = np.zeros(p + 1)
        c[i] = 1.0
        vals[i] = L.legval(x, c)
        dc = L.legder(c)
        if dc.size == 0:
            derivs[i] = 0.0
        else:
            derivs[i] = L.legval(x, dc)
    return vals, derivs


class DGSpace:
    """Precomputed reference-element data for a Q_p tensor Legendre DG space."""

    def __init__(self, p, nq, nfq):
        self.p = p
        self.ndof = (p + 1) ** 2

        # ---- volume quadrature (tensor Gauss-Legendre on [-1,1]^2) -------
        xq, wq = L.leggauss(nq)
        self.xq, self.wq = xq, wq
        Bv, dBv = basis_1d(p, xq)          # (p+1, nq)

        ndof = self.ndof
        Phi = np.zeros((ndof, nq, nq))
        dPhi_dxi = np.zeros((ndof, nq, nq))
        dPhi_deta = np.zeros((ndof, nq, nq))
        k = 0
        for i in range(p + 1):
            for j in range(p + 1):
                Phi[k] = np.outer(Bv[i], Bv[j])
                dPhi_dxi[k] = np.outer(dBv[i], Bv[j])
                dPhi_deta[k] = np.outer(Bv[i], dBv[j])
                k += 1
        self.Phi = Phi
        self.dPhi_dxi = dPhi_dxi
        self.dPhi_deta = dPhi_deta
        self.W = np.outer(wq, wq)          # (nq,nq) volume weights

        # ---- face quadrature (1D Gauss-Legendre on [-1,1]) ---------------
        xf, wf = L.leggauss(nfq)
        self.xf, self.wf = xf, wf
        Bf, _ = basis_1d(p, xf)             # (p+1, nfq)  transverse basis
        Bm1, _ = basis_1d(p, np.array([-1.0]))
        Bp1, _ = basis_1d(p, np.array([1.0]))

        def edge_phi(edge):
            out = np.zeros((ndof, nfq))
            k = 0
            for i in range(p + 1):
                for j in range(p + 1):
                    if edge == 'left':      # xi = -1, vary eta
                        out[k] = Bm1[i, 0] * Bf[j]
                    elif edge == 'right':    # xi = +1
                        out[k] = Bp1[i, 0] * Bf[j]
                    elif edge == 'bottom':   # eta = -1, vary xi
                        out[k] = Bf[i] * Bm1[j, 0]
                    elif edge == 'top':      # eta = +1
                        out[k] = Bf[i] * Bp1[j, 0]
                    k += 1
            return out

        self.Phi_left = edge_phi('left')
        self.Phi_right = edge_phi('right')
        self.Phi_bottom = edge_phi('bottom')
        self.Phi_top = edge_phi('top')

        # local-index (i,j) -> flat k,  needed nowhere else explicitly since
        # ordering k = i*(p+1)+j is used consistently throughout.


# ============================================================================
# 4. MESH
# ============================================================================

class Mesh:
    def __init__(self, n_mu, n_z, Z):
        self.n_mu, self.n_z = n_mu, n_z
        self.mu_edges = np.linspace(-1.0, 1.0, n_mu + 1)
        self.z_edges = np.linspace(0.0, Z, n_z + 1)

    def cell(self, a, b):
        return (self.mu_edges[a], self.mu_edges[a + 1],
                self.z_edges[b], self.z_edges[b + 1])


# ============================================================================
# 5. ASSEMBLY
# ============================================================================

def gdof(a, b, local_k, n_mu, ndof):
    """Global dof index of local dof `local_k` in cell (a,b)."""
    return (b * n_mu + a) * ndof + local_k


def assemble(mesh, sp_space):
    n_mu, n_z = mesh.n_mu, mesh.n_z
    ndof = sp_space.ndof
    ntot = n_mu * n_z * ndof

    rows, cols, vals = [], [], []
    F = np.zeros(ntot)

    xq, wq, W = sp_space.xq, sp_space.wq, sp_space.W
    Phi, dPhi_dxi, dPhi_deta = sp_space.Phi, sp_space.dPhi_dxi, sp_space.dPhi_deta

    # ---------------- 5.1 volume integrals -------------------------------
    for b in range(n_z):
        z0, z1 = mesh.z_edges[b], mesh.z_edges[b + 1]
        hz = z1 - z0
        Zc = z0 + 0.5 * (xq + 1.0) * hz              # (nq,) physical z at quad pts
        dlz = dlogn_dz(Zc)                             # (nq,)
        kap = kappa_func(Zc)                            # (nq,)
        for a in range(n_mu):
            mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
            hmu = mu1 - mu0
            MU = mu0 + 0.5 * (xq + 1.0) * hmu           # (nq,) physical mu at quad pts
            J = hmu * hz / 4.0

            bz2 = MU[:, None] * np.ones((1, len(xq)))          # (m,n) = mu[m]
            bmu2 = dlz[None, :] * (1.0 - MU[:, None] ** 2)      # (m,n)
            kap2 = kap[None, :] * np.ones((len(xq), 1))          # (m,n)

            dPhi_dmu = dPhi_dxi * (2.0 / hmu)
            dPhi_dz = dPhi_deta * (2.0 / hz)

            Integrand = (bz2[None, :, :] * dPhi_dz
                         + bmu2[None, :, :] * dPhi_dmu
                         + kap2[None, :, :] * Phi)

            A_local = J * np.einsum('mn,kmn,imn->ik', W, Integrand, Phi)

            Fval = f_rhs(MU[:, None], Zc[None, :]) * np.ones((len(xq), len(xq)))
            F_local = J * np.einsum('mn,mn,imn->i', W, Fval, Phi)

            g0 = (b * n_mu + a) * ndof
            gidx = g0 + np.arange(ndof)
            rr, cc = np.meshgrid(gidx, gidx, indexing='ij')
            rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(A_local.ravel())
            F[gidx] += F_local

    # ---------------- 5.2 interior vertical faces (const mu) -------------
    # separates cell A=(a-1,b) [minus/lower mu] and B=(a,b) [plus/higher mu]
    xf, wf = sp_space.xf, sp_space.wf
    PhiL, PhiR = sp_space.Phi_left, sp_space.Phi_right
    for b in range(n_z):
        z0, z1 = mesh.z_edges[b], mesh.z_edges[b + 1]
        hz = z1 - z0
        Zf = z0 + 0.5 * (xf + 1.0) * hz
        wgt = wf * (hz / 2.0)
        for a in range(1, n_mu):
            mu_a = mesh.mu_edges[a]
            s = dlogn_dz(Zf) * (1.0 - mu_a ** 2)      # (nfq,)  b.n_A

            gA0 = ((b) * n_mu + (a - 1)) * ndof
            gB0 = ((b) * n_mu + a) * ndof
            idxA = gA0 + np.arange(ndof)
            idxB = gB0 + np.arange(ndof)

            PhiA = PhiR                 # A's trace uses its right edge
            PhiB = PhiL                 # B's trace uses its left edge

            for f in range(len(xf)):
                sf, wfi = s[f], wgt[f]
                if sf >= 0.0:            # B inflow
                    BB = sf * wfi * np.outer(PhiB[:, f], PhiB[:, f])
                    BA = -sf * wfi * np.outer(PhiB[:, f], PhiA[:, f])
                    rr, cc = np.meshgrid(idxB, idxB, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(BB.ravel())
                    rr, cc = np.meshgrid(idxB, idxA, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(BA.ravel())
                else:                     # A inflow
                    AA = -sf * wfi * np.outer(PhiA[:, f], PhiA[:, f])
                    AB = sf * wfi * np.outer(PhiA[:, f], PhiB[:, f])
                    rr, cc = np.meshgrid(idxA, idxA, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(AA.ravel())
                    rr, cc = np.meshgrid(idxA, idxB, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(AB.ravel())

    # ---------------- 5.3 interior horizontal faces (const z) ------------
    # separates cell A=(a,b-1) [minus/lower z] and B=(a,b) [plus/higher z]
    PhiBo, PhiTo = sp_space.Phi_bottom, sp_space.Phi_top
    for a in range(n_mu):
        mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
        hmu = mu1 - mu0
        MUf = mu0 + 0.5 * (xf + 1.0) * hmu
        wgt = wf * (hmu / 2.0)
        for b in range(1, n_z):
            s = MUf.copy()               # (nfq,)  b.n_A = mu

            gA0 = ((b - 1) * n_mu + a) * ndof
            gB0 = ((b) * n_mu + a) * ndof
            idxA = gA0 + np.arange(ndof)
            idxB = gB0 + np.arange(ndof)

            PhiA = PhiTo                 # A's trace uses its top edge
            PhiB = PhiBo                 # B's trace uses its bottom edge

            for f in range(len(xf)):
                sf, wfi = s[f], wgt[f]
                if sf >= 0.0:            # B inflow
                    BB = sf * wfi * np.outer(PhiB[:, f], PhiB[:, f])
                    BA = -sf * wfi * np.outer(PhiB[:, f], PhiA[:, f])
                    rr, cc = np.meshgrid(idxB, idxB, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(BB.ravel())
                    rr, cc = np.meshgrid(idxB, idxA, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(BA.ravel())
                else:                     # A inflow
                    AA = -sf * wfi * np.outer(PhiA[:, f], PhiA[:, f])
                    AB = sf * wfi * np.outer(PhiA[:, f], PhiB[:, f])
                    rr, cc = np.meshgrid(idxA, idxA, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(AA.ravel())
                    rr, cc = np.meshgrid(idxA, idxB, indexing='ij')
                    rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(AB.ravel())

    # ---------------- 5.4 physical boundary faces -------------------------
    # mu = -1 and mu = +1 :  b.n == 0 identically -> no contribution.

    # z = 0  (bottom edge of cells b=0), inflow where mu>0  (s = -mu < 0)
    b = 0
    z0 = mesh.z_edges[0]
    for a in range(n_mu):
        mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
        hmu = mu1 - mu0
        MUf = mu0 + 0.5 * (xf + 1.0) * hmu
        wgt = wf * (hmu / 2.0)
        s = -MUf
        g0 = (b * n_mu + a) * ndof
        idx = g0 + np.arange(ndof)
        Aloc = np.zeros((ndof, ndof))
        Floc = np.zeros(ndof)
        for f in range(len(xf)):
            sf = s[f]
            if sf < 0.0:
                wfi = wgt[f]
                gf = g_bc(MUf[f], z0)
                Aloc += (-sf) * wfi * np.outer(PhiBo[:, f], PhiBo[:, f])
                Floc += (-sf) * wfi * gf * PhiBo[:, f]
        rr, cc = np.meshgrid(idx, idx, indexing='ij')
        rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(Aloc.ravel())
        F[idx] += Floc

    # z = Z  (top edge of cells b=n_z-1), inflow where mu<0  (s = mu < 0)
    b = n_z - 1
    z1 = mesh.z_edges[-1]
    for a in range(n_mu):
        mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
        hmu = mu1 - mu0
        MUf = mu0 + 0.5 * (xf + 1.0) * hmu
        wgt = wf * (hmu / 2.0)
        s = MUf.copy()
        g0 = (b * n_mu + a) * ndof
        idx = g0 + np.arange(ndof)
        Aloc = np.zeros((ndof, ndof))
        Floc = np.zeros(ndof)
        for f in range(len(xf)):
            sf = s[f]
            if sf < 0.0:
                wfi = wgt[f]
                gf = g_bc(MUf[f], z1)
                Aloc += (-sf) * wfi * np.outer(PhiTo[:, f], PhiTo[:, f])
                Floc += (-sf) * wfi * gf * PhiTo[:, f]
        rr, cc = np.meshgrid(idx, idx, indexing='ij')
        rows.append(rr.ravel()); cols.append(cc.ravel()); vals.append(Aloc.ravel())
        F[idx] += Floc

    rows = np.concatenate(rows)
    cols = np.concatenate(cols)
    vals = np.concatenate(vals)
    A = sp.coo_matrix((vals, (rows, cols)), shape=(ntot, ntot)).tocsr()
    return A, F


# ============================================================================
# 6. SOLUTION EVALUATION / POST-PROCESSING
# ============================================================================

def eval_solution(mesh, sp_space, U, mu_pts, z_pts):
    """Evaluate the DG solution at arbitrary points (mu_pts, z_pts) (broadcastable)."""
    mu_pts = np.atleast_1d(np.asarray(mu_pts, dtype=float))
    z_pts = np.atleast_1d(np.asarray(z_pts, dtype=float))
    n_mu, n_z = mesh.n_mu, mesh.n_z
    ndof = sp_space.ndof
    p = sp_space.p
    out = np.zeros(mu_pts.shape)

    a_idx = np.clip(np.searchsorted(mesh.mu_edges, mu_pts, side='right') - 1, 0, n_mu - 1)
    b_idx = np.clip(np.searchsorted(mesh.z_edges, z_pts, side='right') - 1, 0, n_z - 1)

    for i in range(mu_pts.size):
        a, b = a_idx[i], b_idx[i]
        mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
        z0, z1 = mesh.z_edges[b], mesh.z_edges[b + 1]
        xi = 2.0 * (mu_pts[i] - mu0) / (mu1 - mu0) - 1.0
        eta = 2.0 * (z_pts[i] - z0) / (z1 - z0) - 1.0
        Bxi, _ = basis_1d(p, np.array([xi]))
        Beta, _ = basis_1d(p, np.array([eta]))
        g0 = (b * n_mu + a) * ndof
        val = 0.0
        k = 0
        for ii in range(p + 1):
            for jj in range(p + 1):
                val += U[g0 + k] * Bxi[ii, 0] * Beta[jj, 0]
                k += 1
        out[i] = val
    return out


def build_plot_grid(mesh, sp_space, U, nplot=6):
    """Build a fine structured grid (with cell-local discontinuities preserved)
    of the DG solution for visualisation with pcolormesh/contour."""
    n_mu, n_z = mesh.n_mu, mesh.n_z
    p = sp_space.p
    ndof = sp_space.ndof
    xs = np.linspace(-1.0, 1.0, nplot)
    Bxs, _ = basis_1d(p, xs)                     # (p+1, nplot)

    MU = np.zeros((n_z * nplot, n_mu * nplot))
    ZZ = np.zeros_like(MU)
    UU = np.zeros_like(MU)

    for b in range(n_z):
        z0, z1 = mesh.z_edges[b], mesh.z_edges[b + 1]
        zloc = z0 + 0.5 * (xs + 1.0) * (z1 - z0)
        for a in range(n_mu):
            mu0, mu1 = mesh.mu_edges[a], mesh.mu_edges[a + 1]
            muloc = mu0 + 0.5 * (xs + 1.0) * (mu1 - mu0)
            g0 = (b * n_mu + a) * ndof
            Uloc = U[g0:g0 + ndof].reshape(p + 1, p + 1)   # [i(mu-index), j(z-index)]
            # value at (xi_m, eta_n) = sum_ij Uloc[i,j]*Bxs[i,m]*Bxs[j,n]
            val = np.einsum('ij,im,jn->mn', Uloc, Bxs, Bxs)  # shape (nplot_mu, nplot_z)
            MU[b * nplot:(b + 1) * nplot, a * nplot:(a + 1) * nplot] = muloc[None, :].T * 0 + \
                np.tile(muloc.reshape(-1, 1), (1, nplot))
            ZZ[b * nplot:(b + 1) * nplot, a * nplot:(a + 1) * nplot] = np.tile(zloc.reshape(1, -1), (nplot, 1)).T
            UU[b * nplot:(b + 1) * nplot, a * nplot:(a + 1) * nplot] = val.T
    return MU, ZZ, UU


# ============================================================================
# 7. MAIN DRIVER
# ============================================================================

def solve(p_deg=P_DEG, n_mu=N_MU, n_z=N_Z, Z=Z_DOMAIN, nq=NQ, nfq=NFQ, verbose=True):
    mesh = Mesh(n_mu, n_z, Z)
    space = DGSpace(p_deg, nq, nfq)
    A, F = assemble(mesh, space)
    if verbose:
        print(f"Assembled system: {A.shape[0]} DOFs, {A.nnz} nonzeros "
              f"(p={p_deg}, N_mu={n_mu}, N_z={n_z})")
    U = spla.spsolve(A.tocsc(), F)
    if verbose:
        print(f"Solve done. ||u||_inf = {np.max(np.abs(U)):.6g}")
    return mesh, space, U


if __name__ == "__main__":
    mesh, space, U = solve()

    # ---- quick sanity print: compare u to boundary data g=mu near Sigma --
    test_mu = np.array([-0.8, -0.4, 0.2, 0.6, 0.9])
    u0 = eval_solution(mesh, space, U, test_mu, 1e-6 * np.ones_like(test_mu))
    print("\nNear z=0 (inflow expected only for mu>0):")
    for m, val in zip(test_mu, u0):
        print(f"  mu={m:+.2f}:  u(mu,0+) = {val:+.4f}   (BC g=mu -> {m:+.4f})")

    uZ = eval_solution(mesh, space, U, test_mu, (mesh.z_edges[-1] - 1e-6) * np.ones_like(test_mu))
    print(f"\nNear z=Z={mesh.z_edges[-1]} (inflow expected only for mu<0):")
    for m, val in zip(test_mu, uZ):
        print(f"  mu={m:+.2f}:  u(mu,Z-) = {val:+.4f}   (BC g=mu -> {m:+.4f})")

    # ---- plot ----------------------------------------------------------
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        MU, ZZ, UU = build_plot_grid(mesh, space, U, nplot=6)
        fig, ax = plt.subplots(figsize=(6, 5))
        pc = ax.pcolormesh(MU, ZZ, UU, shading='auto', cmap='viridis')
        fig.colorbar(pc, ax=ax, label=r'$u(\mu,z)$')
        ax.set_xlabel(r'$\mu$')
        ax.set_ylabel(r'$z$')
        ax.set_title('DG solution of the transport equation')
        fig.tight_layout()
        fig.savefig("dg_solution.png", dpi=150)
        print("\nSaved plot to dg_solution.png")
    except ImportError:
        print("matplotlib not available; skipping plot.")
